version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - C:/upload:/usr/share/nginx/html:ro  # Windows 경로를 nginx 경로와 연결
    restart: always

  upload_container:
    image: eggzuxi/uploadapi:latest
    container_name: upload_container
    ports:
      - "8080:8080"
    environment:
      - com.tripwhiz.uploadBasic=/app/upload
      - spring.multipart.location=/app/upload
      - spring.datasource.url=jdbc:mariadb://10.10.10.92:13306/tripwhiz
    volumes:
      - C:/upload:/app/upload
