services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "/C:/zzz/upload:/uploads"  # 호스트의 C:/zzz/upload 디렉토리를 컨테이너의 /uploads에 마운트
      - "/C:/zzz/tripwhiz-user-back/nginx/nginx.conf:/etc/nginx/nginx.conf"